### ISSUE TITLE
One lib archive or two?

### ISSUE THREAD

**Issue by daschaich** [primme/primme#1]
Hello,

I've been using v1.1 for years, and just tried out v1.2.1 today.  I had some trouble linking until I noticed that `make libz` now splits routines between libprimme.a and libzprimme.a rather than putting everything into libzprimme.a as I was used to.  I'm mentioning this in an issue rather than a pull request since I'm not sure whether it's a bug or a new design paradigm...  However, the fact that ZSRC routines go into libprimme.a while the COMMONSRC routines go into libzprimme.a makes me suspect the former.

Another reason I didn't bother with a pull request is that it's a simple one-character fix if it is indeed something to be fixed: Change line 38 of PRIMMESRC/Makefile from
make -C ZSRC lib;\
to
make -C ZSRC libz;\
(and similarly for libd on line 28).

**Comment by stathopoulos** [comment]
Thank you for your comment. You are right, this is not by design. The ranlib puts everything in libprimme.a instead of the libzprimme.a. It will be corrected promptly in a small update.

**Comment by stathopoulos** [comment]
Cool! You can close discussions.

A
