### ISSUE TITLE
python binding ignores LDFLAGS

### ISSUE THREAD

**Issue by yurivict** [primme/primme#14]
I'm trying to create a FreeBSD port for the python binding: https://pypi.org/project/primme/
FreeBSD requires some special LDFLAGS to be passed to the link commands, but the external LDFLAGS variable is ignored.

**Comment by eromero-vlc** [comment]
I'm not able to reproduce the problem on my linux environment. If I do

LDFLAGS=-lgfortran make python 

or

make python LDFLAGS=-lgfortran

or Make_flags is modified, the flags are included on the linking of the python module. In the particular case of the python binding, the linking of the python module is made by python's distutil, and it is the one including the flags from the env variables. Maybe there's a bug there.

Anyway you can inject linking flags by modifying Python/setup.py. For instance, you can add a line like that:

extra_options['extra_link_args'].append('-lmyflags -W,l another_flag')

at setup.py line 66:

https://github.com/primme/primme/blob/master/Python/setup.py#L66

Thanks for making the port. And let me know if we can help.

**Comment by yurivict** [comment]
> extra_options['extra_link_args'].append('-lmyflags -W,l another_flag')

The problem occurs inside of the line: ```lapack_info = get_info('lapack_opt')```.
There doesn't appear to be an easy way to pass ```extra_link_args``` to it.

**Comment by eromero-vlc** [comment]
numpy controls those flags and they can be altered by a configuration file with name site.cfg sited with setup.py or on ~/.numpy-site.cfg. If you need to add specific flags there, you can try to add them like this:

[all]
rpath = mypath_for_libs:other_paths_for_libs

or

[lapack]
library_dirs = path_to_lapack

Check out the example that numpy provides:
https://github.com/numpy/numpy/blob/master/site.cfg.example

**Comment by yurivict** [comment]
This clarified the problem, thanks!
