### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by yurivict** [primme/primme#16]
```
In file included from primme/src/svds/primme_svds_interfacedouble.c:3:
In file included from primme/src/svds/primme_svds_interface.c:41:
In file included from primme/src/include/numerical.h:36:
primme/src/include/template.h:106:4: error: "An arithmetic should be selected, please define one of USE_DOUBLE, USE_DOUBLECOMPLEX, USE_FLOAT or USE_FLOATCOMPLEX."
#  error "An arithmetic should be selected, please define one of USE_DOUBLE, USE_DOUBLECOMPLEX, USE_FLOAT or USE_FLOATCOMPLEX."
   ^
In file included from primme/src/svds/primme_svds_interfacedouble.c:3:
In file included from primme/src/svds/primme_svds_interface.c:41:
In file included from primme/src/include/numerical.h:36:
In file included from primme/src/include/template.h:372:
/usr/include/malloc.h:3:2: error: "<malloc.h> has been replaced by <stdlib.h>"
#error "<malloc.h> has been replaced by <stdlib.h>"
 ^
```

Please note that the ```<malloc.h>``` header has been discontinued, see here for Linux: https://linux.die.net/man/3/malloc

OS: FreeBSD 11.2

**Comment by jxy** [comment]
In addition to the fix #17 for excluding the malloc.h.  You will have two more problems on FreeBSD.

1. `src/tools/dependencies` need to call `python2.7`
2. C11 complex support is not complete on the base libm.  The compilation will complain the nonexistent `clog`, `cexpl`, etc.  I ended up using openlibm.

**Comment by yurivict** [comment]
Are you able to make master build on FreeBSD?

**Comment by jxy** [comment]
Yes.  I have been using PRIMME on FreeBSD.

**Comment by eromero-vlc** [comment]
Compiler may complain that cexp or clog is not declared, but PRIMME will not use the complex version of these functions. It is expansion of the tgmath.h macros the one causing the warnings.

**Comment by yurivict** [comment]
Ok, thanks, I got it running.
