### ISSUE TITLE
The shared library needs -fPIC

### ISSUE THREAD

**Issue by yurivict** [primme/primme#22]
Otherwise, the link fails:
```
/usr/bin/ld: eigs/auxiliary_eigsfloat.o: relocation R_X86_64_32 against `a local symbol' can not be used when making a shared object; recompile with -fPIC
```

**Comment by eromero-vlc** [comment]
Can you put -fPIC in CFLAGS?

**Comment by yurivict** [comment]
> Can you put -fPIC in CFLAGS?

This is what I did. But all appropriate flags should be set by the project, this is why I created this bug.
