### ISSUE TITLE
Unable to install primme in python

### ISSUE THREAD

**Issue by Passero86** [primme/primme#27]
I have tried different versions of primme, but still I cannot install it on my computer.

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing c:\users\xxx\downloads\primme-2.2.zip
    ERROR: Command errored out with exit status 1:
     command: 'c:\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-req-build-5v1x_2yg\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-req-build-5v1x_2yg\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\xxx\AppData\Local\Temp\pip-req-build-5v1x_2yg\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\anaconda3\lib\tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-req-build-5v1x_2yg\\setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by primme** [comment]
The package version 2.x is not working with recent versions of numpy. I have uploaded a new version to PyPI, primme 3.0.1. If it is not available in https://pypi.tuna.tsinghua.edu.cn/simple, you can download the package primme-3.0.1.tar.gz from https://pypi.org/project/primme/#files and then do

`pip install ./primme-3.0.1.tar.gz`
