### ISSUE TITLE
unable to install primme in matlab @ windows 10

### ISSUE THREAD

**Issue by paedk** [primme/primme#28]
Matlab2018b, Windows10, MEX configured to use 'MinGW64 Compiler (C)' 

Running make.m gives me the error

MEX cannot find library 'mwlapack', specified with the -l option.
 MEX searched for a file with one of the following names:
 libmwlapack.lib
 mwlapack.lib
 Verify the library name is correct. If the library is not
 on the existing path, specify the path with the -L option.

I'm sure the libs are available as the [mathworks mex examples](https://nl.mathworks.com/help/matlab/matlab_external/standalone-example.html;jsessionid=1029c3b495e316fc33b1a74febea) run through fine.

**Comment by eromero-vlc** [comment]
I have upload some changes into master that should fix the issue. Give them a try and let me know!

**Comment by paedk** [comment]
it seems to work fine now. thanks !
