### ISSUE TITLE
Python `primme.eigsh` parallelization support

### ISSUE THREAD

**Issue by stephenhky** [primme/primme#36]
I have a huge symmetric real sparse matrix that I will need to solve a eigenproblem on. I am using Python 3.

However, in the input parameters of `primme.eigsh`, there is nothing to specify the parallelization. Does it automatically support parallel computing? Or is there somewhere else i can enforce parallel computing when running `primme.eigsh`? Thanks.

**Comment by stephenhky** [comment]
I have a Python code that does something else, but there is a line that computes the eigenvalues and eigenvectors of a huge but very sparse matrix. Although the matrix is already very sparse, it still takes time to solve the eigenproblem with just one core.

Yes, I am running this in a cluster. It would be nice if the Python interface allows computation with multicores.

**Comment by eromero-vlc** [comment]
What python package are you using to store the matrix?

**Comment by stephenhky** [comment]
It is in scipy: `scipy.sparse.dok_matrix`. However, I can store it as other types of sparse matrices inside scipy without breaking my code, such as `csr_matrix` or `csc_matrix`.

**Comment by eromero-vlc** [comment]
If you are using scipy/numpy, eigsh should be using all available cores 
on the node already. You can check this, by running `top` while eigsh is 
running.

scipy does not support distributed matrices (MPI). So you are limited to 
use a single node.

**Comment by stephenhky** [comment]
Oh that is sad.... I have to use sparse matrix. How about sparse tensor in pytorch?

**Comment by eromero-vlc** [comment]
I haven't used pytorch. The documentation says that they support MPI, 
but I am not sure if they allow the tensors to be distributed among 
different processes. If you are able to make your code work with pytorch 
with MPI, I can push a little changes on PRIMME's eigsh to make it work 
with pytorch.

**Comment by stephenhky** [comment]
It looks like they have this previously addressed: https://github.com/pytorch/pytorch/issues/17369

Let me rewrite my code using sparse tensor in pytorch... (maybe some readjustment) and then try primme.eigsh once it can deal with tensors.

**Comment by stephenhky** [comment]
I managed to make a torch sparse COO matrix.

**Comment by eromero-vlc** [comment]
Does it run with mpi? If that's the case, can you share the code with me?

**Comment by stephenhky** [comment]
I am unsure if pytorch sparse matrix in particular supports MPI, although a lot of parts of pytorch definitely support MPI.

Here is where I called `primme.eigsh` for now: https://github.com/stephenhky/PySeqSC/blob/primme/pyseqsc/cachedseq.py#L79
I used scipy sparse matrix here.

I can make an equivalent pytorch matrix pretty easily.

Or is there any python sparse matrix type that supports MPI while primme supports as well?

**Comment by eromero-vlc** [comment]
Well, I didn't expose the MPI part of the interface for eigsh because I didn't see MPI being heavily used by python users. I am only aware of the high-performance frameworks PETSc and PyTrilinos that support distributed matrices. But they don't have very pythonic interfaces ;) and you may need to have some notions about distributed applications. In your case, you probably need to change a lot how the matrix is generated. pytorch's tensors seems easy to use and, for that, I am skeptical that they have good support for MPI. But if you want to try, first you need to compile pytorch to have support for MPI. Then, create a small matrix in pytorch, multiply by some vectors, and check if you get the same results using different number of processes.

Have you used MPI before? Do you know how to run MPI applications? Are you intended to run this on clusters (several machines connected by a fast network)?

**Comment by stephenhky** [comment]
I have not used MPI before and honestly I do not know much about it. But yes, I intend to run all these on clusters.

**Comment by eromero-vlc** [comment]
MPI and distributed systems are not complicated but you need to be aware of what's happening. I strongly recommend to play a little bit with MPI on python first, and follow some tutorial for mpi4py, for instance:

https://mpi4py.readthedocs.io/en/stable/index.html

https://rabernat.github.io/research_computing/parallel-programming-with-mpi-for-python.html

It is very useful to try to implement something simple by yourself. Try to distribute vectors among all the processes and then do the dot product.

**Comment by stephenhky** [comment]
Thanks for the information. I am checking it out.

**Comment by stephenhky** [comment]
Hi I would like to confirm.... is PRIMME.eigsh able to take PetSC sparse matrices?

**Comment by eromero-vlc** [comment]
primme.eigsh can take as a matrix any object following the [LinearOperator](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.LinearOperator.html#scipy-sparse-linalg-linearoperator) interface taken as input and output numpy matrices.

I don't think PETSc Mat object follows LinearOperator, but it should be possible to write down a function that copies the input vector into a PETSc's Vec, does the multiplication and returns the result as a numpy vector.

Once you have that function you can do:
```
A = scipy.sparse.linalg.LinearOperator((n,n), matvec=mymatvec, matmat=mymatvec)
evals, evecs = primme.eigsh(A, 3, tol=1e-6, which='LA')
```

**Comment by stephenhky** [comment]
Thanks for the clarification.
