### ISSUE TITLE
PRIMME is not on CRAN

### ISSUE THREAD

**Issue by mdozmorov** [primme/primme#38]
It appears PRIMME is [gone from CRAN](https://cran.r-project.org/web/packages/PRIMME/index.html) due to some unresolved problems. PRIMME is the driving engine of our [SpectralTAD](https://bioconductor.org/packages/SpectralTAD/) package, and [TADCompare](https://bioconductor.org/packages/TADCompare/) package that depends on SpectralTAD. Both are broken for the moment.

Per [Bioconductor package guidelines](https://www.bioconductor.org/developers/package-guidelines/), all dependencies must satisfy "All packages must be available via Bioconductor or CRAN; users and the automated build system have no way to install packages from other sources.". 

Are there any plans to put PRIMME back on CRAN?  Or, any other advice?
CC @cresswellkg

**Comment by eromero-vlc** [comment]
I have already resubmitted the patched package. It should be back soon.

Thanks for let us know this!

**Comment by mdozmorov** [comment]
Thank you, @eromero-vlc, will be checking CRAN.

**Comment by mdozmorov** [comment]
It looks like PRIMME is back on CRAN. Our packages are building. Thanks, @eromero-vlc.

**Comment by eromero-vlc** [comment]
Happy to help! And sorry for the inconvenience!

**Comment by eromero-vlc** [comment]
fucking cran... let me see what I can do

**Comment by eromero-vlc** [comment]
I've submitted a new version. The R package should be back in a couple of days. Thanks for letting us know!

**Comment by mdozmorov** [comment]
Thank you, great! Yes, let's hope CRAN won't have more issues.
