### ISSUE TITLE
Uncounted matrix-vector multiplications with blocksize 1 in the beginning of a calculation

### ISSUE THREAD

**Issue by robertrueger** [primme/primme#4]
When calculating only a small number of eigenvectors using the JD_Olsen_plusK method (didn't test others), primme seems to do a number of matrix-vector multiplications of blocksize 1 in the beginning of a calculation, which are not counted in stats.numMatvecs.

I noticed this because our method that does the matrix-vector multiplication also prints some information about the progress of the calculation. At the beginning of every matrix-vector-multiplication, it prints stats.numOuterIterations, stats.numMatvecs and the number of converged eigenvectors (stored in initSize).

Here is some example output for the diagonalization of a 11664x11664 matrix for which the lowest 14 eigenvectors were calculated. maxBlockSize was set to 14, maxBasisSize was set to 140 and maxRestartSize was automatically set to 56 by primme.

```
Cycle:     0, MatVecs:      0 (BLK:  14), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     42 (BLK:  14), Conv:     0 /    14
Cycle:     1, MatVecs:     56 (BLK:  14), Conv:     0 /    14
Cycle:     2, MatVecs:     70 (BLK:  14), Conv:     0 /    14
Cycle:     3, MatVecs:     84 (BLK:  14), Conv:     0 /    14
Cycle:     4, MatVecs:     98 (BLK:  14), Conv:     0 /    14
Cycle:     5, MatVecs:    112 (BLK:  14), Conv:     0 /    14
Cycle:     6, MatVecs:    126 (BLK:  14), Conv:     0 /    14
Cycle:     7, MatVecs:    140 (BLK:  14), Conv:     0 /    14
Cycle:     8, MatVecs:    154 (BLK:  14), Conv:     0 /    14
Cycle:     9, MatVecs:    168 (BLK:   8), Conv:     0 /    14
Cycle:    10, MatVecs:    176 (BLK:   4), Conv:     0 /    14
Cycle:    11, MatVecs:    180 (BLK:   4), Conv:     0 /    14
Cycle:    12, MatVecs:    184 (BLK:   4), Conv:     0 /    14
Cycle:    13, MatVecs:    188 (BLK: ---), Conv:    14 /    14
```

(Note that the last line was printed after primme finished.)

So after the first matrix-vector multiplication with blocksize 14 there is a series of matrix-vector multiplications with blocksize 1 which do not count towards the total number of matrix-vector multiplications.

I found this rather surprising. It also seems quite inefficient to me in cases where there is a certain constant-time overhead in starting a matrix-vector multiplication, which is only amortized with a large blocksize. Is this working as intended?

**Comment by eromero-vlc** [comment]
Thanks for reporting this subtle detail. Well, these matvecs of 
blocksize 1 at the beginning are not counted immediately, but they are 
counted at once. See how the matvecs counter passes from 14 to 42 just 
after the series of matvecs of blocksize 1.

Cycle:     0, MatVecs:     14 (BLK:   1), Conv:     0 /    14
Cycle:     0, MatVecs:     42 (BLK:  14), Conv:     0 /    14

This is already changed in master.

**Comment by robertrueger** [comment]
Ah, I see!

I don't really know what's happening there, but I assume it's not possible to do these in a blocked fashion? (My matrix-vector multiplication is generally more efficient for larger block sizes.)

**Comment by eromero-vlc** [comment]
These matvecs come from building a block Krylov subspace that will be 
added to the initial search subspace. Currently this space is built 
vector by vector, because it's easy and it's only done once, but we can 
do better if blocksize>1. We'll consider that.

**Comment by zhoujxtu** [comment]
Help me.  When I use the primme  in matlab version.
When I type make matlab  in the command window, 
list:
I can't find file `primme_mex'. I don't know how to solve this problem

**Comment by stathopoulos** [comment]
Did you include the directory /Your path to/primme/Matlab in your Matlab’s path?
Please give us some more information about your installation.

Andreas

**Comment by eromero-vlc** [comment]
The issue has fixed in recent versions.
