### ISSUE TITLE
How to limit memory usage in Python Interface

### ISSUE THREAD

**Issue by aaeberharter** [primme/primme#44]
I am calling `primme` like that:

```primme.eigsh(H, k=1, which='SA', v0 = psi, tol=1.e-15, return_eigenvectors=True)```

Where `H` is a real symmetric sparse matrix and subclass of `scipy.sparse.linalg.LinearOperator`.

I think I really need this low tolerance for my algorithm to work properly. The program runs in an environment with limited memory and in some cases the above call to `eigsh` allocates too much memory so that it crashes.

If I try to limit the number of basis states allocated by passing `ncv = 8` to `eigsh` the memory requirement is lower, however sometimes it gets stuck (does not converge).

If the parameter `maxiter = 500` is also passed to `eigsh` then it will definitely return after 500 matvecs, however in some cases it does not return an approximate eigenvalue eigenvector pair.

Is the behavior as outlined above intended for `eigsh` ?
How should I call `eigsh` for limited memory usage ?

**Comment by eromero-vlc** [comment]
It is going to be difficult to speedup the convergence without increasing the memory requirements. But first, it is helpful if you can send us the convergence for ncv=8 and maxiter=1000. For that, run primme asking to return stats and history, and send us the output of `s` or the result of the `pprint` to email if it's too big:

```python
import pprint
evals, evecs, s = primme.eigsh(H, k=1, which='SA', v0 = psi, tol=1.e-15, return_eigenvectors=True, return_stats=True,return_history=True)
# Print convergence table
print("MV Time Eval Res") 
pprint.pprint(list(zip(s['hist']['numMatvecs'], s['hist']['elapsedTime'], s['hist']['eval'], s['hist']['resNorm'])))
```

**Comment by aaeberharter** [comment]
Is it possible to get an approximate eigenpair from `primme` even when there is no convergence after `maxiter` iterations?
The outermost loop of my algorithm is able to deal with that as long as it is a good approximation.

I have the logs you requested attached to this message.

Thank you for your dedication.
[primme_1.log](https://github.com/primme/primme/files/6221358/primme_1.log)
[primme_2.log](https://github.com/primme/primme/files/6221360/primme_2.log)

**Comment by eromero-vlc** [comment]
You can clearly see that the residual does not reduce much after 20 iterations achieving a relative residual tolerance of 8e-15 (you asked 1e-15). The eigensolver is converging very fast. So the most likely reason for the stagnation is that the numerical errors of the matvec, the inner products, the orthogonalization... are preventing to reduce the residual norm further. You may consider to increase the tolerance to 1e-14.

I have updated master and primme package in pip with a new option, `return_unconverged`, that when it is `True`, `eigsh` returns also unconverged eigenvalues and vectors. Check it out, and let me know if that works.

```python
evals, evecs = primme.eigsh(H, k=1, which='SA', v0 = psi, tol=1.e-15,
                            maxiter=40, return_eigenvectors=True, return_unconverged=True)
```

**Comment by aaeberharter** [comment]
Thank you very much the `return_unconverged` feature is very helpful and probably all I need. From my side this issue is solved for now.
