### ISSUE TITLE
eigsh (python): return_eigenvectors has no effect

### ISSUE THREAD

**Issue by jcmgray** [primme/primme#48]
Currently, setting ``return_eigenvectors=False`` returns the eigenvectors regardless. It would be an easy fix to simply not return them (for compatbility with ``scipy``), not sure if one might save some computation too? Happy to submit PR.

**Comment by eromero-vlc** [comment]
Yes, that's a mistake at the end of the function eigsh in primme.pyx. Unfortunately PRIMME has to compute the eigenvectors anyway.

We gladly take PR!
