### ISSUE TITLE
Support for time limit

### ISSUE THREAD

**Issue by DavidAce** [primme/primme#51]
I am trying to find a way to halt iterations of `dprimme` if a maximum time is reached.

I have tried using `primme.monitorFun(...)`: According to the documentation, I should be able to [set `ierr` to a nonzero value to stop the current call to primme](http://www.cs.wm.edu/~andreas/software/doc/appendix.html#c.primme_params.monitorFun), but doing so triggers an assertion error: 
```
include/../eigs/auxiliary_eigs_normal.c:485: int monitorFun_dprimme(dummy_type_dprimme *, int, int *, int *, int, dummy_type_dprimme *, int, dummy_type_dprimme *, int, int *, dummy_type_dprimme *, int, dummy_type_dprimme, const char *, double, primme_event, double, primme_context): 
Assertion `__err==0' failed.
```

Is there some other way to achieve this?

In terms of a feature request, I think ideally this could be introduced as a field `double primme_params::maxTime` which enables a time limit if set to a positive value (in seconds).

**Comment by eromero-vlc** [comment]
There's an easy way of doing this if you are using the C or the Fortran interface. In the matvec function or in convTestFun or in monitorFun, set primme.maxMatvecs to zero when primme.stats.elapsedTime > maxTime. When that happens, primme exits almost immediately and dprimme should return the error code -3 (PRIMME_MAIN_ITER_FAILURE).
