### ISSUE TITLE
Accessing 'ShiftsForPreconditioner' Field in Python `primme.eigsh`

### ISSUE THREAD

**Issue by lightpeak008** [primme/primme#52]
Hello everyone!
I was trying to use `primme.eigsh` with extra arguments via `**kargs`. When I added 'ShiftsForPreconditioner' as an arguemnt, I get the following error:

    Traceback (most recent call last):
      File "primme.pyx", line 555, in primme.eigsh
      File "primme.pyx", line 156, in primme.__primme_params_set
    ValueError: Invalid field 'b'ShiftsForPreconditioner''

Backtracking through the source code, I noticed that in `/src/eigs/primme_interface.c`'s  `primme_member_info` routine, for 'ShiftsForPreconditioner' the value of `arity` is set to 0 (Line 1592-1594).

      case PRIMME_targetShifts:
      case PRIMME_ShiftsForPreconditioner:
      if (type) *type = primme_double;
      if (arity) *arity = 0;
      break;

But the Python Interface's `primme.pyx` requires it to be 1 (Line 155-156)

        if r != 0  or arity != 1:
            raise ValueError("Invalid field '%s'" % field_)
I believe that this is the cause of the error.
Is this behaviour intentional? Is it possible to use 'ShiftsForPreconditioner' in Python Interface?

Also, can I request a change in the documentation for primme.eigsh() under the Python Interface to include a description for `**kargs`? I did not notice its existence for so long!

**Comment by eromero-vlc** [comment]
ShiftsForPreconditioner is an array of suggested shifts for generating the preconditioner. It is provided to the user during the computation of eigenvalues. See a more detailed description in http://www.cs.wm.edu/~andreas/software/doc/appendix.html#c.primme_params.ShiftsForPreconditioner

So it does not make sense for the user to provide a value for ShiftsForPreconditioner on the call of eigsh.

Unfortunately, with the current interface, the user does not have access to ShiftsForPreconditioner during the execution of eigsh. Unless the preconditioner can be reconstructed very cheaply, this feature is not helpful anyway.

Thanks, S Shri Hari, for pointing out that we don't document all extra parameters that the user can pass. We will work on this!

**Comment by lightpeak008** [comment]
Thank you for the reply! I misunderstood it to be an array the user has to allocate and give it to primme to access the shifts.

Actually, I was looking into implementing the diagonalization routines similar to the ones used in Quantum ESPRESSO's PWSCF, which uses a diagonal preconditioner array that is dependent on the approximate eigenvalues computed in the previous iteration within the diagonalization routine.

I think if I need this feature, I would have to modify the interface itself i.e `primme.pyx` file and compile it. This was my original plan, until I noticed the `**kargs' in the signature of `primme.eigs`. I would like to know if it possible to access the 'ShiftsForPreconditioner' array using the `primme_params_get_object` in `primme.pyx`.

And as for the documentation, a simple addition mentioning the `**kargs` and directing the reader to the C Interface parameters would be sufficient.

**Comment by eromero-vlc** [comment]
No, primme_params_get_object will not do it. I don't think there's a function for that on primme.pyx.

But if you need it, I can do it. I can create a function that will give you the value of a field while running primme. That can be useful for other users.

**Comment by lightpeak008** [comment]
A function that would allow access to fields during the runtime of primme routines would be beneficial! I don't fully understand the interface, and I need to access the field for better preconditioning. So, if you could write one, that will be really helpful.
Thank you!

**Comment by eromero-vlc** [comment]
I pushed the changes into master that extend the python interface to access to ShiftsForPreconditioner. Check out the examples in examples.py and in the documentation of `get_eigsh_param`.

```
# Get PRIMME properties within a callback
def convtest_rel_Anorm(eval, evec, rnorm):
   estimateAnorm = primme.get_eigsh_param('stats_estimateLargestSVal')
   return rnorm <= estimateAnorm * 1e-3
evals, evecs = primme.eigsh(A, 3, which='LA', convtest=convtest_rel_Anorm)

def P(x):
   # The scipy.sparse.linalg.LinearOperator constructor may call this function giving a vector
   # as input; detect that case and return whatever
   if x.ndim == 1:
      return x / A.diagonal()
   shifts = primme.get_eigsh_param('ShiftsForPreconditioner')
   y = np.copy(x)
   for i in range(x.shape[1]): y[:,i] = x[:,i] / (A.diagonal() - shifts[i])
   return y
Pop = scipy.sparse.linalg.LinearOperator(A.shape, matvec=P, matmat=P)
evals, evecs = primme.eigsh(A, 3, OPinv=Pop, tol=1e-3, which='LA')
```

**Comment by lightpeak008** [comment]
I was able to run the example code and test it. The example showed clearly how to use `get_eigsh_param`. As I am working on other changes in my code, I couldn't try the new preconditioning. I'll get back to you for feedback soon, once I implement and test the new feature. Till then, I'll keep this issue open, just in case I encounter any other problems. I'll also change the title to better represent the issue and the added feature.
Again, Thanks a lot for sorting this issue quickly!

**Comment by eromero-vlc** [comment]
Happy to help! Let us know any further issues.
