### ISSUE TITLE
"Wrong" const qualifiers in R/src/primmeR.cpp

### ISSUE THREAD

**Issue by jaganmn** [primme/primme#71]
Hi - I'm a co-author of R package **Matrix**.  I've just cleaned up our C API somewhat and noticed that we wrongly used `const` qualifiers in arguments 1, 3, 4, and 5 of our declaration of `M_cholmod_sdmult`.  You call `M_cholmod_sdmult` here,

https://github.com/primme/primme/blob/645dfac3c47f5e852ae9623f81a5b95374f54fba/R/src/primmeR.cpp#L565

and here,

https://github.com/primme/primme/blob/645dfac3c47f5e852ae9623f81a5b95374f54fba/R/src/primmeR.cpp#L1129-L1130

where in both cases `ONEf` and `ZEROf` have type `const double[2]`.  A corollary is that **PRIMME** installation fails if we remove the `const` qualifiers from our prototype, as I am wanting to do.

Can you change to using just `double[2]` there?  I'll revert my prototype fix until you do so, to avoid problems with CRAN.  It's not urgent, so maybe just reply when it's safe to reinstate the fix ...

Thanks.

**Comment by jaganmn** [comment]
Incidentally, I am hoping to eventually deprecate both `Matrix_isclass_ge_dense` and `Matrix_isclass_Csparse`, which you also use in `primmeR.cpp`.  You could define and use the following instead ...

```
#include <Rinternals.h>
int is_ge(SEXP x)
{
    static const char *valid[] = { "ngeMatrix", "lgeMatrix", "dgeMatrix", "" };
    return R_check_class_etc(x, valid) >= 0;
}
int is_Csparse(SEXP x)
{
    static const char *valid[] = {
        "ngCMatrix", "lgCMatrix", "dgCMatrix",
        "nsCMatrix", "lsCMatrix", "dsCMatrix",
        "ntCMatrix", "ltCMatrix", "dtCMatrix", "" };
    return R_check_class_etc(x, valid) >= 0;
}
```

**Comment by eromero-vlc** [comment]
Thanks for let us know! Can you take a quick look to these changes?

https://github.com/primme/primme/commit/541d59eaa3c558afdb6a29d190e7c75a05ffac5f

Do I need to change also `(const_CHM_DN)&chx`?

**Comment by jaganmn** [comment]
I've checked out the branch - I can confirm that it solves the problems backwards compatibly (i.e., it passes its checks independently of the changes in Matrix).  Still, yes, do replace `const_CHM_*` with `CHM_*`, so that I may remove the `const_CHM_*` types altogether, as **PRIMME** is the only package that used them.  It would be convenient, but not strictly necessary, to have the patched version of **PRIMME** submitted before we submit Matrix 1.6-2 in mid-October. I can always delay the changes in Matrix if necessary.

Thanks very much for the fast response!

**Comment by eromero-vlc** [comment]
I made the changes and submitted the package. It should be published in a few days.
Let me know if you find more issues
