### ISSUE TITLE
DepreciationWarning and new release

### ISSUE THREAD

**Issue by MoiseRousseau** [primme/primme#73]
I installed PRIMME Python interface from this repo:
```
git clone https://github.com/primme/primme
cd primme
make
cd Python
pip install .
```
However, when running example.py, I got into the warning:
```
DeprecationWarning: Please use `aslinearoperator` from the `scipy.sparse.linalg` namespace, the `scipy.sparse.linalg.interface` namespace is deprecated.
```

To fix it, changing the `scipy.sparse.linalg.interface` to `scipy.sparse.linalg` in `primme.c` and `primme.pyx` fixes the problem, something such as:
```
sed -i 's/scipy\.sparse\.linalg\.interface/scipy\.sparse\.linalg/g' primme.c primme.pyx
```

Can you fix the problem on the repo ? Also, can you create a new release on GitHub with the latest development ?

Moise

**Comment by eromero-vlc** [comment]
We have released a new version that fixed the issue. Thanks for reporting!
