### ISSUE TITLE
`convTestFun` documentation is out-of-date

### ISSUE THREAD

**Issue by jeremy-myers** [primme/primme#74]
I noticed this difference in SVDS for the convergence test function. `int *method` does not appear to be documented?:
* Documentation: `void (*convTestFun)(double *sval, void *leftsvec, void *rightsvec, double *rNorm, int *isconv, primme_svds_params *primme_svds, int *ierr)`
* Interface: `void (*convTestFun_v)(double *sval, void *leftsvec, void *rightsvec, double *rNorm, int *method, int *isconv, struct primme_svds_params *primme, int *ierr);`

**Comment by stathopoulos** [comment]
I think you can simply ignore the method.

**Comment by eromero-vlc** [comment]
the description of the parameter `method` was missing. I just pushed a commit to fix it. Thanks @jeremy-myers !
