### ISSUE TITLE
can primme run magma with HIP?

### ISSUE THREAD

**Issue by jsboer** [primme/primme#77]
Hi, I find in make_flags implying that run with magma must use CUDA, does this true? If so, does this mean we can only run multi-GPUs in nvidia GPUs? Thank you!

**Comment by eromero-vlc** [comment]
The magma interface is being deprecated and only supports nvidia gpus. The cublas_{s,d,c,z}primme supports Nvidia and AMD gpus.

And in any case, primme does not support multi-gpu directly. One has to run an mpi process on each gpu.

**Comment by jsboer** [comment]
> The magma interface is being deprecated and only supports nvidia gpus. The cublas_{s,d,c,z}primme supports Nvidia and AMD gpus.
> 
> And in any case, primme does not support multi-gpu directly. One has to run an mpi process on each gpu.

Hi! Is there an example to show a mixed use of hip and mpi? The mpi example show the way to implement y=AX by petsc. If mix the hip and mpi, what could be the  easiest way to achieve？ Is that use GPU version of petsc?

**Comment by eromero-vlc** [comment]
There is nothing special about using MPI together with HIP besides making sure that each process picks a different gpu.

If your matvec doesn't use MPI already, it may not be trivial to parallelize it with MPI. If your matvec is not efficient or does not have gpu support, then going through PETSc can be a good option.

The PETSc C example supports CUDA and should be easy to update for ROCm (pending task). But the Fortran PETSc example doesn't support gpus at all. However, looking at the C example, it shouldn't be difficult to update it (another pending task). Just my fortran is rusty and I don't know how well hip supports fortran.

**Comment by jsboer** [comment]
> There is nothing special about using MPI together with HIP besides making sure that each process picks a different gpu.
> 
> If your matvec doesn't use MPI already, it may not be trivial to parallelize it with MPI. If your matvec is not efficient or does not have gpu support, then going through PETSc can be a good option.
> 
> The PETSc C example supports CUDA and should be easy to update for ROCm (pending task). But the Fortran PETSc example doesn't support gpus at all. However, looking at the C example, it shouldn't be difficult to update it (another pending task). Just my fortran is rusty and I don't know how well hip supports fortran.

I see, thank you!
