### ISSUE TITLE
Python 3.11 Compilation Error

### ISSUE THREAD

**Issue by mikZych** [primme/primme#81]
Using Python 3.11, I get:
```
primme.cpp:198:12: fatal error: longintrepr.h: No such file or directory
        198 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
compilation terminated.
```
Presumably because In Python3.11 longintepr.h got moved to /usr/include/python3.11/cpython/longintrepr.h.
On Python3.10 everything is fine.

**Comment by eromero-vlc** [comment]
We have uploaded a new version of the package, primme 3.2.2. Can you check if you still have the same error?

**Comment by mikZych** [comment]
The error is gone. Everything works perfectly for me now. Thanks
