### ISSUE TITLE
Tests fail with dynamic library

### ISSUE THREAD

**Issue by andreasnoack** [primme/primme#9]
Simply
```
make solib test
```
fails on Ubuntu 16.10 with
```
andreasnoack@anubis:~/.julia/v0.7/Primme/deps/primme$ make test
------------------------------------------------
 Test C examples
------------------------------------------------
make[1]: Entering directory '/home/andreasnoack/.julia/v0.7/Primme/deps/primme/examples'
cc -O -fPIC -DNDEBUG -DF77UNDERSCORE  -I../include -c ex_eigs_dseq.c -o ex_eigs_dseq.o
cc -o ex_eigs_dseq ex_eigs_dseq.o -L../lib -I../include -lprimme -llapack -lblas -lm -gfortran
cc -O -fPIC -DNDEBUG -DF77UNDERSCORE  -I../include -c ex_eigs_zseq.c -o ex_eigs_zseq.o
cc -o ex_eigs_zseq ex_eigs_zseq.o -L../lib -I../include -lprimme -llapack -lblas -lm -gfortran
cc -O -fPIC -DNDEBUG -DF77UNDERSCORE  -I../include -c ex_svds_dseq.c -o ex_svds_dseq.o
cc -o ex_svds_dseq ex_svds_dseq.o -L../lib -I../include -lprimme -llapack -lblas -lm -gfortran
cc -O -fPIC -DNDEBUG -DF77UNDERSCORE  -I../include -c ex_svds_zseq.c -o ex_svds_zseq.o
cc -o ex_svds_zseq ex_svds_zseq.o -L../lib -I../include -lprimme -llapack -lblas -lm -gfortran
=========== Executing ./ex_eigs_dseq
./ex_eigs_dseq: error while loading shared libraries: libprimme.so: cannot open shared object file: N
o such file or directory
=========== Executing ./ex_eigs_zseq
./ex_eigs_zseq: error while loading shared libraries: libprimme.so: cannot open shared object file: N
o such file or directory
=========== Executing ./ex_svds_dseq
./ex_svds_dseq: error while loading shared libraries: libprimme.so: cannot open shared object file: N
o such file or directory
=========== Executing ./ex_svds_zseq
./ex_svds_zseq: error while loading shared libraries: libprimme.so: cannot open shared object file: N
o such file or directory
Some tests fail. Please consider to send us the file
examples/tests.log if the software doesn't work as expected.
Makefile:56: recipe for target 'test_examples_C' failed
make[1]: *** [test_examples_C] Error 1
make[1]: Leaving directory '/home/andreasnoack/.julia/v0.7/Primme/deps/primme/examples'
makefile:29: recipe for target 'test' failed
make: *** [test] Error 2
```
If I delete the `.so` (such that the static library is loaded) then it works.

I also think the so is not correctly linked to `LIBS` so when it is `dlopen`ed, the LAPACK symbols are not found.

**Comment by eromero-vlc** [comment]
Yes, multiplatform linking is complicated. We offer a very limited 
example, but it is up to the user/application to set the proper linking 
options. For instance in Linux, you can set 
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib before executing the tests. The 
next command should work

make test LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib

For your Julia interface, you may want to skip the make test and test 
only throw the Julia interface. BTW I'm writing down a patch so you can 
link with openblas64_.

**Comment by andreasnoack** [comment]
Wouldn't CMake be useful for this?

The reason I started looking into this was https://travis-ci.org/andreasnoack/Primme.jl#L340 which motivated the last sentence. When creating the `so`, I believe you should link the dependencies such that the dependent libraries are loaded when `libprimme.so` is loaded.

> BTW I'm writing down a patch so you can link with openblas64_.

Awesome

**Comment by eromero-vlc** [comment]
The next error is not exactly a problem with linking flags:
`/home/travis/julia/bin/julia: symbol lookup error: /home/travis/.julia/v0.7/Primme/src/../deps/primme/lib/libprimme.so: undefined symbol: dsyevx_`

It's because OpenBLAS functions names compiled with ILP64 have the suffix _64. With the last change in master you can compile PRIMME for OpenBlas ILP64 with:

`make solib CFLAGS="-DPRIMME_BLAS_SUFFIX=_64 -DPRIMME_BLASINT_SIZE=64 -O -fPIC"`

**Comment by andreasnoack** [comment]
Using OpenBLAS would be great so thanks again for adding this feature. However, my point is that linker flags should be appended to https://github.com/primme/primme/blob/master/src/Makefile#L103. If that had happened then `libprimme.so` would just have loaded the system LAPACK on Travis.

**Comment by andreasnoack** [comment]
This is after using OpenBLAS https://travis-ci.org/andreasnoack/Primme.jl#L340 so the problem persists. It goes away if I add `-lopenblas64_ -L $(Base.JULIA_HOME)/../lib` to https://github.com/primme/primme/blob/master/src/Makefile#L103

**Comment by eromero-vlc** [comment]
I think you're right. I've seen what other Julia packages do, and it seems there's not much options. See for instance, https://github.com/JuliaOpt/SCS.jl/blob/master/deps/build.jl.

Ok, so my last change allows that the linking flags can be passed with LDFLAGS.

**Comment by andreasnoack** [comment]
Great. With this, I'm now able to make the tests pass https://travis-ci.org/andreasnoack/Primme.jl
